### ISSUE TITLE
java.util.concurrent.RejectedExecutionException

### ISSUE THREAD

**Issue by tobijanssen** [tobijanssen/GSOPlan#10]
java.util.concurrent.RejectedExecutionException: pool=0/1, queue=0
at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:1961)
at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:794)
at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1315)
at java.util.concurrent.Executors$DelegatedExecutorService.execute(Executors.java:602)
at de.janssen.android.gsoplan.SerialExecutor.scheduleNext(SerialExecutor.java:39)
at de.janssen.android.gsoplan.SerialExecutor.execute(SerialExecutor.java:27)
at de.janssen.android.gsoplan.PlanActivity.executeWithDialog(PlanActivity.java:240)
at de.janssen.android.gsoplan.PlanActivity.checkAvailibilityOfWeek(PlanActivity.java:153)
at de.janssen.android.gsoplan.PlanActivity.refreshWeek(PlanActivity.java:529)
at de.janssen.android.gsoplan.PlanActivity.onOptionsItemSelected(PlanActivity.java:453)
at android.app.Activity.onMenuItemSelected(Activity.java:2205)
at com.android.internal.policy.impl.PhoneWindow.onMenuItemSelected(PhoneWindow.java:777)
at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:143)
at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:855)
at com.android.internal.view.menu.IconMenuView.invokeItem(IconMenuView.java:532)
at com.android.internal.view.menu.IconMenuItemView.performClick(IconMenuItemView.java:122)
at android.view.View$PerformClick.run(View.java:9112)
at android.os.Handler.handleCallback(Handler.java:587)
at android.os.Handler.dispatchMessage(Handler.java:92)
at android.os.Looper.loop(Looper.java:130)
at android.app.ActivityThread.main(ActivityThread.java:3835)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:507)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:864)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:622)
at dalvik.system.NativeStart.main(Native Method)

**Comment by tobijanssen** [comment]
problem in Version 1.02 Beta gefixt. Update ist public
