### ISSUE TITLE
IllegalStateException: ListPreference requires an entries array and an entryValues array.

### ISSUE THREAD

**Issue by tobijanssen** [tobijanssen/GSOPlan#18]
java.lang.RuntimeException: Unable to start activity ComponentInfo{de.janssen.android.gsoplan/de.janssen.android.gsoplan.activities.AppPreferences}: java.lang.IllegalStateException: ListPreference requires an entries array and an entryValues array.
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1651)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1667)
at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:2836)
at android.app.ActivityThread.access$1600(ActivityThread.java:117)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:939)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:130)
at android.app.ActivityThread.main(ActivityThread.java:3687)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:507)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:842)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.IllegalStateException: ListPreference requires an entries array and an entryValues array.
at android.preference.ListPreference.onPrepareDialogBuilder(ListPreference.java:186)
at android.preference.DialogPreference.showDialog(DialogPreference.java:293)
at android.preference.DialogPreference.onRestoreInstanceState(DialogPreference.java:441)
at android.preference.ListPreference.onRestoreInstanceState(ListPreference.java:252)
at android.preference.Preference.dispatchRestoreInstanceState(Preference.java:1552)
at android.preference.PreferenceGroup.dispatchRestoreInstanceState(PreferenceGroup.java:320)
at android.preference.PreferenceGroup.dispatchRestoreInstanceState(PreferenceGroup.java:320)
at android.preference.Preference.restoreHierarchyState(Preference.java:1534)
at android.preference.PreferenceActivity.onRestoreInstanceState(PreferenceActivity.java:145)
at android.app.Activity.performRestoreInstanceState(Activity.java:816)
at android.app.Instrumentation.callActivityOnRestoreInstanceState(Instrumentation.java:1096)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1629)
... 12 more

**Comment by tobijanssen** [comment]
Wird verursacht durch: 
ListPreference anzeigen lassen > rotate screen > crash

**Comment by tobijanssen** [comment]
Fix: PreferenceActivity sollte nicht neu erstellt werden bei einem Screen-Rotate.
-> AndroidManifest.xml
