### ISSUE TITLE
java.lang.RuntimeException bei Handler.<init>()

### ISSUE THREAD

**Issue by tobijanssen** [tobijanssen/GSOPlan#7]
HTC One X
HTC One V

Stack traces
v1.00 Beta
Nov 19, 2012 3:16:10 PM

android.view.InflateException: Binary XML file line #4: Error inflating class android.widget.ListView
at android.view.LayoutInflater.createView(LayoutInflater.java:606)
at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:56)
at android.view.LayoutInflater.onCreateView(LayoutInflater.java:653)
at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:678)
at android.view.LayoutInflater.rInflate(LayoutInflater.java:739)
at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
at android.view.LayoutInflater.inflate(LayoutInflater.java:352)
at de.janssen.android.gsoplan.Tools.createPage(Tools.java:108)
at de.janssen.android.gsoplan.Tools.appendTimeTableToPager(Tools.java:54)
at de.janssen.android.gsoplan.PlanActivity.initViewPager(PlanActivity.java:346)
at de.janssen.android.gsoplan.PlanActivity.selfCheck(PlanActivity.java:553)
at de.janssen.android.gsoplan.runnables.PlanActivityLuncher.run(PlanActivityLuncher.java:15)
at de.janssen.android.gsoplan.SerialExecutor.run(SerialExecutor.java:49)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
at java.lang.Thread.run(Thread.java:864)
Caused by: java.lang.reflect.InvocationTargetException
at java.lang.reflect.Constructor.constructNative(Native Method)
at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
at android.view.LayoutInflater.createView(LayoutInflater.java:586)
... 16 more
Caused by: java.lang.RuntimeException: Can't create handler inside thread that has not called Looper.prepare()
at android.os.Handler.<init>(Handler.java:121)
at android.view.GestureDetector$GestureHandler.<init>(GestureDetector.java:262)
at android.view.GestureDetector.<init>(GestureDetector.java:382)
at android.view.GestureDetector.<init>(GestureDetector.java:359)
at android.view.GestureDetector.<init>(GestureDetector.java:343)
at android.widget.ListView.<init>(ListView.java:345)
at android.widget.ListView.<init>(ListView.java:289)

**Comment by tobijanssen** [comment]
Kann ich leider nicht reproduzieren.
Hat aber evtl. etwas damit zu tun, dass nicht vom der MainThread versucht wird den Content zu ändern.

evtl. Fix: Aufruf der Funktion appendTimeTableToPager über Handler

Muss getestet werden

**Comment by tobijanssen** [comment]
problem in Version 1.02 Beta gefixt. Update ist public
