### ISSUE TITLE
Keine Abfrage moglich

### ISSUE THREAD

**Issue by exylian** [tobijanssen/GSOPlan#9]
Leider kann der Stundenplan der VTF24 und auch von vielen anderen nicht abgerufen werden.
Keiner Verbindung zum Server oder gar leere error message

**Comment by tobijanssen** [comment]
Danke für den Hinweis!
Das werde ich so schnell wie möglich fixen.
Update kommt im Laufe der Woche

**Comment by tobijanssen** [comment]
java.lang.IllegalArgumentException: View not attached to window manager
at android.view.WindowManagerImpl.findViewLocked(WindowManagerImpl.java:355)
at android.view.WindowManagerImpl.removeView(WindowManagerImpl.java:200)
at android.view.Window$LocalWindowManager.removeView(Window.java:432)
at android.app.Dialog.dismissDialog(Dialog.java:278)
at android.app.Dialog.access$000(Dialog.java:71)
at android.app.Dialog$1.run(Dialog.java:111)
at android.app.Dialog.dismiss(Dialog.java:268)
at de.janssen.android.gsoplan.runnables.UpdateTimeTableList.run(UpdateTimeTableList.java:60)
at android.os.Handler.handleCallback(Handler.java:587)
at android.os.Handler.dispatchMessage(Handler.java:92)
at android.os.Looper.loop(Looper.java:123)
at android.app.ActivityThread.main(ActivityThread.java:3687)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:507)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:625)
at dalvik.system.NativeStart.main(Native Method)
